bayan: FileList Class Reference
FileList Class Reference
Class FileList - creates the first list of files to search for duplicates.
#include <FileList.h>
Public Member Functions
FileList (const SearchParameters &params)
file_list_type get_file_list ()
std::vector< std::string > get_file_names ()
Private Member Functions
void build_file_list ()
bool is_match_filename (const std::string &filename)
bool is_excluded_dir (const fs::path &path)
Private Attributes
std::size_t _file_id {0}
std::vector< std::string > _file_names
file_list_type _file_list
const SearchParameters & _params
std::vector< boost::regex > _regex_list
Detailed Description
Class FileList - creates the first list of files to search for duplicates.
Parameters
params A link to a class SearchParameters containing the parameters required for the search.
Definition at line 20 of file FileList.h.
Constructor & Destructor Documentation
FileList()
FileList::FileList (const SearchParameters & params) explicit
Definition at line 5 of file FileList.cpp.
                                                 : _params(params) {
    for (const auto& regex : _params.get_file_regex()) {
        _regex_list.emplace_back(regex);
    }
    build_file_list();
}
Member Function Documentation
build_file_list()
void FileList::build_file_list () private
Definition at line 12 of file FileList.cpp.
{
    for (const auto& dir : _params.get_dirs()) {
        try {
            fs::path path(dir);
            for (fs::recursive_directory_iterator it(path, fs::directory_options::skip_permission_denied);
                 it != fs::recursive_directory_iterator(); it++) {
                if (fs::is_regular_file(it->path())) {
                    if (file_size(it->path()) >= _params.get_min_file_size() &&
                            is_match_filename(it->path().filename().string())) {
                        if (_file_list.count(file_size(it->path())) == 1) {
                            _file_list[file_size(it->path())].emplace_back(_file_id);
                        } else {
                            _file_list.emplace(file_size(it->path()), std::vector<std::size_t>{_file_id});
                        }
                        _file_names.push_back(it->path().string());
                        ++_file_id;
                    }
                } else if (fs::is_directory(it->path())) {
                    if (it.depth() >= _params.get_max_depth() || is_excluded_dir(it->path())) {
                        it.disable_recursion_pending();
                    }
                }
            }
        } catch (const std::exception& exception) {
            std::cerr << "Incorrect search directory: " << dir << std::endl;
        }
    }
}
Referenced by FileList().
get_file_list()
file_list_type FileList::get_file_list ()
Definition at line 68 of file FileList.cpp.
{
    return _file_list;
}
Referenced by DuplicateSearch::DuplicateSearch().
get_file_names()
std::vector< std::string > FileList::get_file_names ()
Definition at line 72 of file FileList.cpp.
{
    return _file_names;
}
Referenced by DuplicateSearch::DuplicateSearch().
is_excluded_dir()
bool FileList::is_excluded_dir (const fs::path & path) private
Definition at line 54 of file FileList.cpp.
{
    for (const auto& ex_dir : _params.get_excluded_dirs()) {
        if (ex_dir == path.filename().string()) {
            return true;
        }
    }
    for (const auto& ex_dir_full : _params.get_excluded_dirs_full()) {
        if (fs::equivalent(path, fs::path(ex_dir_full))) {
            return true;
        }
    }
    return false;
}
Referenced by build_file_list().
is_match_filename()
bool FileList::is_match_filename (const std::string & filename) private
Definition at line 41 of file FileList.cpp.
{
    if (_regex_list.empty()) {
        return true;
    }
    boost::smatch result;
    for (const auto& regex : _regex_list) {
        if (boost::regex_match(filename, result, regex)) {
            return true;
        }
    }
    return false;
}
Referenced by build_file_list().
Member Data Documentation
_file_id
std::size_t FileList::_file_id {0} private
Definition at line 32 of file FileList.h.
Referenced by build_file_list().
_file_list
file_list_type FileList::_file_list private
Definition at line 34 of file FileList.h.
Referenced by build_file_list(), and get_file_list().
_file_names
std::vector<std::string> FileList::_file_names private
Definition at line 33 of file FileList.h.
Referenced by build_file_list(), and get_file_names().
_params
const SearchParameters& FileList::_params private
Definition at line 35 of file FileList.h.
Referenced by build_file_list(), FileList(), and is_excluded_dir().
_regex_list
std::vector<boost::regex> FileList::_regex_list private
Definition at line 36 of file FileList.h.
Referenced by FileList(), and is_match_filename().
The documentation for this class was generated from the following files:
FileList.h
FileList.cpp