bayan: SearchParameters Class Reference
SearchParameters Class Reference
Class SearchParameters - prepares the parameters for the search.
#include <SearchParameters.h>
Public Member Functions
SearchParameters (int argc, char **argv)
std::vector< std::string > get_dirs () const
std::vector< std::string > get_excluded_dirs () const
std::vector< std::string > get_excluded_dirs_full () const
int get_max_depth () const
unsigned int get_min_file_size () const
std::vector< std::string > get_file_regex () const
unsigned int get_block_size () const
HashAlgo get_hash_algo () const
Static Private Member Functions
static std::size_t replace_all (std::string &inout, std::string_view what, std::string_view with)
static std::string make_regex (std::string &file_mask)
Private Attributes
std::vector< std::string > _dirs
std::vector< std::string > _excluded_dirs
std::vector< std::string > _excluded_dirs_full
int _max_depth {0}
unsigned int _min_file_size {1}
std::vector< std::string > _file_regex
unsigned int _block_size {8}
HashAlgo _hash_algo {HashAlgo::MurMurHash2}
Detailed Description
Class SearchParameters - prepares the parameters for the search.
Parameters
argc Number of command line parameters.
argv Array of command line parameters.
Definition at line 18 of file SearchParameters.h.
Constructor & Destructor Documentation
SearchParameters()
SearchParameters::SearchParameters (int argc, char ** argv)
Definition at line 6 of file SearchParameters.cpp.
{
    std::string last_key;
    for (int i = 1; i < argc; ++i) {
        if (argv[i][0] == '-') {
            last_key = std::string(argv[i]);
        } else {
            if (last_key == "-d") {
                _dirs.emplace_back(argv[i]);
            } else if (last_key == "-ex") {
                std::string ex_dir(argv[i]);
                std::size_t pos1 = ex_dir.find('/');
                std::size_t pos2 = ex_dir.find('\\');
                if (pos1 != std::string::npos || pos2 != std::string::npos) {
                    _excluded_dirs_full.push_back(ex_dir);
                } else {
                    _excluded_dirs.push_back(ex_dir);
                }
            } else if (last_key == "-l") {
                try {
                    _max_depth = std::stoi(argv[i]);
                } catch (const std::exception& exception) {}
            } else if (last_key == "-ms") {
                try {
                    _min_file_size = std::stoi(argv[i]);
                } catch (const std::exception& exception) {}
            } else if (last_key == "-fm") {
                std::string file_mask(argv[i]);
                _file_regex.push_back(make_regex(file_mask));
            } else if (last_key == "-s") {
                try {
                    _block_size = std::stoi(argv[i]);
                } catch (const std::exception& exception) {}
            } else if (last_key == "-h") {
                std::string hash(argv[i]);
                if (hash == "crc32") {
                    _hash_algo = HashAlgo::CRC32;
                } else if (hash == "md5") {
                    _hash_algo = HashAlgo::MD5;
                }
            }
        }
    }
}
Member Function Documentation
get_block_size()
unsigned int SearchParameters::get_block_size () const
Definition at line 91 of file SearchParameters.cpp.
{
    return _block_size;
}
Referenced by DuplicateSearch::DuplicateSearch().
get_dirs()
std::vector< std::string > SearchParameters::get_dirs () const
Definition at line 67 of file SearchParameters.cpp.
{
    return _dirs;
}
Referenced by FileList::build_file_list().
get_excluded_dirs()
std::vector< std::string > SearchParameters::get_excluded_dirs () const
Definition at line 71 of file SearchParameters.cpp.
{
    return _excluded_dirs;
}
Referenced by FileList::is_excluded_dir().
get_excluded_dirs_full()
std::vector< std::string > SearchParameters::get_excluded_dirs_full () const
Definition at line 75 of file SearchParameters.cpp.
{
    return _excluded_dirs_full;
}
Referenced by FileList::is_excluded_dir().
get_file_regex()
std::vector< std::string > SearchParameters::get_file_regex () const
Definition at line 87 of file SearchParameters.cpp.
{
    return _file_regex;
}
Referenced by FileList::FileList().
get_hash_algo()
HashAlgo SearchParameters::get_hash_algo () const
Definition at line 95 of file SearchParameters.cpp.
{
    return _hash_algo;
}
Referenced by DuplicateSearch::DuplicateSearch().
get_max_depth()
int SearchParameters::get_max_depth () const
Definition at line 79 of file SearchParameters.cpp.
{
    return _max_depth;
}
Referenced by FileList::build_file_list().
get_min_file_size()
unsigned int SearchParameters::get_min_file_size () const
Definition at line 83 of file SearchParameters.cpp.
{
    return _min_file_size;
}
Referenced by FileList::build_file_list().
make_regex()
std::string SearchParameters::make_regex (std::string & file_mask) static private
Definition at line 60 of file SearchParameters.cpp.
{
    replace_all(file_mask, ".", "\\.");
    replace_all(file_mask, "*", ".*");
    replace_all(file_mask, "?", ".{1}");
    return file_mask;
}
Referenced by SearchParameters().
replace_all()
std::size_t SearchParameters::replace_all (std::string & inout, std::string_view what, std::string_view with) static private
Definition at line 50 of file SearchParameters.cpp.
{
    std::size_t count{};
    for (std::string::size_type pos{};
         std::string::npos != (pos = inout.find(what.data(), pos, what.length()));
         pos += with.length(), ++count) {
        inout.replace(pos, what.length(), with.data(), with.length());
    }
    return count;
}
Referenced by make_regex().
Member Data Documentation
_block_size
unsigned int SearchParameters::_block_size {8} private
Definition at line 38 of file SearchParameters.h.
Referenced by get_block_size(), and SearchParameters().
_dirs
std::vector<std::string> SearchParameters::_dirs private
Definition at line 32 of file SearchParameters.h.
Referenced by get_dirs(), and SearchParameters().
_excluded_dirs
std::vector<std::string> SearchParameters::_excluded_dirs private
Definition at line 33 of file SearchParameters.h.
Referenced by get_excluded_dirs(), and SearchParameters().
_excluded_dirs_full
std::vector<std::string> SearchParameters::_excluded_dirs_full private
Definition at line 34 of file SearchParameters.h.
Referenced by get_excluded_dirs_full(), and SearchParameters().
_file_regex
std::vector<std::string> SearchParameters::_file_regex private
Definition at line 37 of file SearchParameters.h.
Referenced by get_file_regex(), and SearchParameters().
_hash_algo
HashAlgo SearchParameters::_hash_algo {HashAlgo::MurMurHash2} private
Definition at line 39 of file SearchParameters.h.
Referenced by get_hash_algo(), and SearchParameters().
_max_depth
int SearchParameters::_max_depth {0} private
Definition at line 35 of file SearchParameters.h.
Referenced by get_max_depth(), and SearchParameters().
_min_file_size
unsigned int SearchParameters::_min_file_size {1} private
Definition at line 36 of file SearchParameters.h.
Referenced by get_min_file_size(), and SearchParameters().
The documentation for this class was generated from the following files:
SearchParameters.h
SearchParameters.cpp