bayan: HashCalculator Class Reference
HashCalculator Class Reference
Class HashCalculator - calculates the hash of a string using a certain algorithm: murmurhash2, crc32, md5.
#include <HashCalculator.h>
Public Member Functions
HashCalculator ()=default
Static Public Member Functions
static std::uint32_t crc32 (const std::string &string)
static std::size_t murmurhash2 (const std::string &string)
static std::string md5_string (const std::string &string)
static duint64_t md5_duint64 (const std::string &string)
Detailed Description
Class HashCalculator - calculates the hash of a string using a certain algorithm: murmurhash2, crc32, md5.
Definition at line 17 of file HashCalculator.h.
Constructor & Destructor Documentation
HashCalculator()
HashCalculator::HashCalculator () default
Member Function Documentation
crc32()
std::uint32_t HashCalculator::crc32 (const std::string & string) static
Definition at line 3 of file HashCalculator.cpp.
{
    boost::crc_32_type result;
    result.process_bytes(string.data(), string.length());
    return result.checksum();
}
Referenced by DuplicateSearch::get_hash().
md5_duint64()
duint64_t HashCalculator::md5_duint64 (const std::string & string) static
Definition at line 24 of file HashCalculator.cpp.
{
    boost::uuids::detail::md5 hash;
    boost::uuids::detail::md5::digest_type digest;
    hash.process_bytes(string.data(), string.size());
    hash.get_digest(digest);
    return { (std::uint64_t)(*(std::uint64_t*)&digest[0]),
             (std::uint64_t)(*(std::uint64_t*)&digest[2]) };
}
Referenced by DuplicateSearch::get_hash().
md5_string()
std::string HashCalculator::md5_string (const std::string & string) static
Definition at line 13 of file HashCalculator.cpp.
{
    boost::uuids::detail::md5 hash;
    boost::uuids::detail::md5::digest_type digest;
    hash.process_bytes(string.data(), string.size());
    hash.get_digest(digest);
    const auto char_digest = reinterpret_cast<const char*>(&digest);
    std::string result;
    boost::algorithm::hex(char_digest, char_digest + sizeof(char_digest), std::back_inserter(result));
    return result;
}
murmurhash2()
std::size_t HashCalculator::murmurhash2 (const std::string & string) static
Definition at line 9 of file HashCalculator.cpp.
{
    return std::hash<std::string>{}(string);
}
Referenced by DuplicateSearch::get_hash().
The documentation for this class was generated from the following files:
HashCalculator.h
HashCalculator.cpp